base.url = https://automationexercise.com
headless.mode = true
docker.remote = true
remote.url.docker = http://localhost:4444/wd/hub

#################### SQL ####################
server=localhost
port=5432
user=postgres
sqlpassword=polo11
